### ISSUE TITLE
Gaussian prior for draw_multinest.m

### ISSUE THREAD

**Issue by ghost** [mattpitkin/matlabmultinest#3]
Hi Matt,

Just thought I'd open this up to discuss the issue of Gaussian priors in draw_multinest.m

Hopefully you have seen my draft patch for that file. The issue I had was that when using a Gaussian prior, the new live points were being excluded when they were below the mean. This is because the range was defined to be in the normalised box 0 to 1, when for a Gaussian they should have a mean of 0 and a standard deviation of 1.

To "fix" this I simply added another condition, saying to only consider whether the drawn point is "in range" if the prior type is not Gaussian. However this on its own effectively reverts the prior back to uniform with no boundaries - because the prior would then have only been useful for the initial set of live points.

I have tried to fix this other issue by calculating the likelihood of the drawn point in the prior, and scaling the likelihood of the drawn point by this amount. I think this should be valid... But I'm not totally sure. It seems to give sensible results for my particular problem, but perhaps you have a better idea for how to deal with it?

Cheers, and thanks for bringing multinest to Matlab!
- Daniel

**Comment by mattpitkin** [comment]
Hi @danielreardon 

Thanks for spotting this problem. I had a look at your [patch](https://github.com/danielreardon/matlabmultinest/commit/dde45283c0a0ff3c601d3a97822a3c11a87afa77), but I think I actually needed a more drastic change to fix this. What I should really have been doing (particularly for the Gaussian prior) was using [inverse transform sampling](https://en.wikipedia.org/wiki/Inverse_transform_sampling) to go from the unit hypercube to the true prior. I've created a new [branch](https://github.com/mattpitkin/matlabmultinest/tree/inverse_transform_sampling) and [commit](https://github.com/mattpitkin/matlabmultinest/commit/90fc490cdc0a135cfe2fe4e83d68a46501c50479) that should fix this. If you could give that a try and let me know if it works for you that would be great.

Cheers,

Matt

**Comment by ghost** [comment]
Hi Matt,

That makes a lot more sense than my attempt, and seems to be working well. Thanks!

Daniel

**Comment by mattpitkin** [comment]
Cool, glad it works. I'll merge this into the main branch. Thanks again for spotting this.
