### ISSUE TITLE
Bug in nestedSampler.m

### ISSUE THREAD

**Issue by DrPaulSharp** [mattpitkin/matlabmultinest#5]
From line 233 of "nested_sampler.m" we have 

```
    if Nmcmc > 0

    . . .

    [livepoints(idx, :), logL(idx)] = draw_mcmc(livepoints, cholmat, ...
      logLmin, prior, data, flike, model, Nmcmc, Nsloppy, ...
      covfrac, diffevfrac, walkfrac, stretchfrac, parnames, ...
      extraparvals);
```

In "draw_mcmc.m" there is a loop running from `i=1:Nmcmc` within a while loop.

If Nmcmc is a vale between 0 and 1, this inner loop is not run, and the code is stuck within an infinite loop. The solution is to change line 233 of "nested_sampler.m" to:

```
if Nmcmc >= 1
```

**Comment by mattpitkin** [comment]
Hi @DrPaulSharp, thanks for your bug report. I'm not sure in what case you would ever get `Nmcmc` having a non-integer value between 0 and 1. I think a better solution would be just to add an error message if the user enters an invalid value.

**Comment by mattpitkin** [comment]
I've now added some additional error checking to make sure valid values of `Nmcmc`, `Nsloppy` and `Nlive` are used.

**Comment by DrPaulSharp** [comment]
Excellent, thank you!
